apiVersion: v1
kind: ConfigMap
metadata:
  name: nginx-config
data:
  default.conf: |
    server {
      listen       8080;
      server_name  localhost;
      location / {
        proxy_pass http://movie-service-service:8000;
      }
      location /casts/ {
        proxy_pass http://cast-service-service:8000/api/v1/casts/;
      }
    }